[package]
name = "rupert-macros"
version = "0.1.0"
authors = ["Moses Palmér <mosespalmer@gmail.com>"]
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1"

[dependencies.syn]
version = "2"
features = ["full", "extra-traits"]
